### ISSUE TITLE
Static not working

### ISSUE THREAD

**Issue by erwinstone** [unicframework/docs#1]
It looks like static is not working, here's the screenshot

![image](https://user-images.githubusercontent.com/96282452/214749081-a218818b-5d4a-4157-b3b2-391ab82c0670.png)

**Comment by rajkumardusad** [comment]
Its working, you have redirect all requests to index.php file. Modify your .htaccess file or use `php -S localhost:8000 index.php` command

**Comment by erwinstone** [comment]
Now it works, thanks
